# Name of the workflow
name: Release

# Run on every commit tag which begins with "v" (e.g., "v0.1.4")
on:
  push:
    tags:
      - "v*"

# Automatically create a GitHub Release, with release details specified (the relevant commits)
jobs:
  release:
    permissions:
      contents: write
    name: "Release"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Build Release
        run: cargo build --release

      - name: Set Executable Permissions
        if: matrix.os == 'ubuntu-latest'
        run: chmod +x target/release/emv_tlv_parser
        
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/release/${{ matrix.os == 'windows-latest' && 'emv_tlv_parser.exe' || 'emv_tlv_parser' }}         
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
